apiVersion: v1
kind: Service
metadata:
    name: { { include "grocery-beep.fullname" . } }
    labels: { { - include "grocery-beep.labels" . | nindent 4 } }
spec:
    type: { { .Values.service.type } }
    ports:
        - port: { { .Values.service.port } }
          targetPort: http
          protocol: TCP
          name: http
    selector: { { - include "grocery-beep.selectorLabels" . | nindent 4 } }
